[package]
name = "mein_http_server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
mime_guess = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
html-escape = "0.2"
chrono = { version = "0.4", features = ["serde"] }

